### ISSUE TITLE
iOS: Keychainwrapper Library is archived, replacement needed

### ISSUE THREAD

**Issue by phal0r** [atroo/capacitor-secure-storage-plugin#1]
Criteria:
- analyze and implement a solution without using the Keychainwrapper Library
- support for auto migration, if the new storage is not compatible

**Comment by laszloblum** [comment]
What are the requirements here?
An updated [capacitor-secure-storage-plugin](https://github.com/atroo/capacitor-secure-storage-plugin#capacitor-secure-storage-plugin) but using a replacement of KeychainWrapper?
What is the minimum supported iOs version?

**Comment by phal0r** [comment]
Yes, exactly. We can make a new major version to clarify this. Keep in mind, that existing data must be supported or migrated. We are on Capacitor 5, so iOS 13 is the minimum version.

**Comment by laszloblum** [comment]
I went through the code and the requirements and my estimation is 24 hours.
I think there would be no extra step for the migration other than the new plugin install.

**Comment by laszloblum** [comment]
The estimation is based on the [KeychainAccess](https://github.com/kishikawakatsumi/KeychainAccess) lib.
