### ISSUE TITLE
Android: Support EncryptedSharedPreferences

### ISSUE THREAD

**Issue by phal0r** [atroo/capacitor-secure-storage-plugin#2]
Criteria:
- add support for EncryptedSharedPreferences
- Capacitor 5 still supports API Level 22, but EncryptedSharedPreferences need API Level 23, so we need to support the old implementation on unsupported devices
- think about auto migration from old storage to EncryptedSharedPreferences on supported devices

**Comment by laszloblum** [comment]
I went through the code and the requirements and my estimation is 16 hours.
I think there would be no extra step for the migration other than the new plugin install.
